### PR TITLE
Fix content negotation

### LINKED ISSUE #16: Content negotiation fails due to live_view templates
Live view interrupts our content negotiation system by injecting a html layout into all of our main views. Normally this is avoided by using different URLS, but this means that `Routes.user_route` helpers don't work.

Should be fixed by using finer-grained plugs.

### PR DESCRIPTION
**Pull request by t0mhaines**
Fixes #16 

* Separates liveview into another plug

* This also fixes 8 tests that had broken when liveview was added - #16

### CODE REVIEW

**Comment by t0mhaines** [comment]
Whoops, specified wrong issue in the commit message

**Comment by nelsonic** [comment]
@th0mas I restarted the build to see if the `mix` error was intermittent. ⏳

**Comment by nelsonic** [comment]
@th0mas while the code update looks good on the surface, I cannot merge it as CI build errors:
https://travis-ci.com/github/dwyl/smart-home-auth-server/builds/178891034
image

Please take a look and re-assign once passing. Thanks. 👍

**Comment by t0mhaines** [comment]
Thats odd, I reran the build at it worked....

The rest of the tests pass in #18 now

**Comment by nelsonic** [comment]
I didn't look at the PR earlier because of this: 
image

But it appears that the build now runs and there is a reduction in the number of tests _failing_. #15 
https://travis-ci.com/github/dwyl/smart-home-auth-server/builds/178891034#L647
image

**Review by nelsonic — APPROVED** [review]
@th0mas looks good (_in the context of on-going test fixing #15_) 👍

**Pull request merged**
